### ISSUE TITLE
endpoint messages

### ISSUE THREAD

**Issue by AndMJ** [ptv1p3r/ptm_api#44]
no endpoint `api/v1/messages/list/userId` esta a vir:

![image](https://user-images.githubusercontent.com/91573182/173421559-86cdee62-df13-4c84-b7dc-315115265f83.png)

queria que viesse o mesmo mas com o numero de mensagens por ver pelo utilizador (mensagens receptionDate = null)

**Comment by ptv1p3r** [comment]
Now returns new attribute totalNotViewed
