### ISSUE TITLE
Intervenções 

### ISSUE THREAD

**Issue by lireupt** [ptv1p3r/ptm_api#51]
Colocar as intervenções com o ID da árvore que o array vem vazio, para se ver na vista da árvore especifica.

![Captura de ecrã 2022-06-22 203829](https://user-images.githubusercontent.com/65983803/175121968-aa517d6d-ec79-4180-8cd3-6b836b03941d.png)

![Captura de ecrã 2022-06-22 203233](https://user-images.githubusercontent.com/65983803/175121587-2a459eea-0d9c-4b42-ba14-bac86f4a0f9d.png)

Na lista está ok.

![Captura de ecrã 2022-06-22 203258](https://user-images.githubusercontent.com/65983803/175121660-98eac9d2-fcd1-41df-8fcc-8679e50aa283.png)

**Comment by ptv1p3r** [comment]
Mas tu tens um endpoint que te retorna as intervenções por treeId, nao e isso que pretendes?
![image](https://user-images.githubusercontent.com/10048793/175258483-d7deeff0-7d17-42ec-ba72-8df95f49a3a0.png)

**Comment by lireupt** [comment]
Sim Pedro, eu pensei que era o end point que identifiquei que trazia a informação da árvore e nao esse que estas a mostrar, mais tarde já volto a ver isso então. Obrigado :D
