### ISSUE TITLE
End Point contadores da Home

### ISSUE THREAD

**Issue by lireupt** [ptv1p3r/ptm_api#52]
- [ ] End point para os contadores onde são apresentados os resultados apurados 

![Captura de ecrã 2022-06-22 224001](https://user-images.githubusercontent.com/65983803/175143552-beee5e67-7e00-4d43-b100-cc5bc3fac38e.png)

**Comment by ptv1p3r** [comment]
Neste momento passas a dispor de um novo endpoint: /api/v1/trees/public/info
que disponibiliza os seguintes contadores (antenção ao nomes):
treesTotal = nr de arvores activas(plantadas)
co2Kg: kg de co2 sequestrado da atmosfera 
H2oLt: Lt de agua bombeada para a atmosfera 
O2Kg: Kg de oxigenio produzido para a atmosfera

Deves incluir por baixo dos contadores e a letra pequena a seguinte mensagem: * Dados medios calculados durante o periodo inicial de 20 anos de vida de uma arvore.
