### ISSUE TITLE
Nomes do Métodos Pagamento

### ISSUE THREAD

**Issue by lireupt** [ptv1p3r/ptm_api#60]
Preciso que revejas os nomes do métodos de pagamento porque o href não reconhece os espaços nem a '/ ' do VISA/Mastercard, ou em alternativa criar um campo tipo com nome do tipo menu 1, menu 2, etc......

EndPoint: api/v1/transaction/methods/list

![Captura de ecrã 2022-06-29 231637](https://user-images.githubusercontent.com/65983803/176561029-c1a4bdef-6484-4c9b-8351-becc6e673230.png)

**Comment by ptv1p3r** [comment]
Como isso é especifico apenas a esse modal e a essa zona não faz sentido mudar na fonte de dados.
Faz o seguinte:
1 º usas o strpos para encontrar na string o caracter "/" : https://www.php.net/manual/en/function.strpos.php
2 º removes o caracter "/" da string, ou seja recebes o "VISA/Mastercard" removes e ficas com "VISAMastercard" sem alterar na fonte de dados que continua com  "VISA/Mastercard" inalterado para outras zonas : https://www.php.net/manual/en/function.substr.php
