### ISSUE TITLE
enpoints de messages

### ISSUE THREAD

**Issue by AndMJ** [ptv1p3r/ptm_api#63]
Faz sentido criar um endpoint para view de messages, mas que nao marque a mensagem como "lida"? 

Basicamente a ideia é que quando estamos no menu "todas as mensagens" e se faz view de uma message qualquer, utilizando o endpoint message/view, a mensagem é marcada como lida, entao para a pessoa que ia receber essa mensagem, essa mensagem ja vai aparecer como "lida". 
Ou entao, em vez de se criar um novo endpoint, o que achas de cada user que esta associado a uma message, ter um campo para se poder marcar como "lida"?

**Comment by ptv1p3r** [comment]
hmm é interessante a tua aproximação ao problema, deixa ca ver o codigo hoje para ter uma ideia mais concreta
